spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/SaintAmeN/aps-configuration.git
          username: pawel.reclaw@gmail.com
          password: v303FFyVcfgFPyIJ7APxsu3
eureka:
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:8010/eureka/